### ISSUE TITLE
JSON Viewer is breaking

### ISSUE THREAD

**Issue by rokrsa** [GetKitsune/application-development-kit#9]
The JSON viewer within the IDE is failing to render the following file:

`{
  "super_app_mode": true,
  "reports": {
    "notifications": [
      {
        "type": "PERIODIC_PERFORMANCE_REPORT",
        "period": 7,
        "email": {
          "body": "periodic_performance_report.html"
        }
      }
    ],
    "settings": {
      "email": {
        "host": "",
        "port": 0,
        "password": "",
        "username": "",
        "ssl_enabled": true
      }
    }
  },
  "payments": {
    "preview": [
      {
        "domain": "example.com",
        "gateway": "paytm",
        "api_secret": "Merchant_ID",
        "api_key": "Account_Secret_Key",
        "redirect_path": "/transaction_status",
        "api_url": "https://pguat.paytm.com",
        "payment_request_endpoint": "/oltp-web/processTransaction",
        "transaction_status_endpoint": "/oltp/HANDLER_INTERNAL/getTxnStatus?JsonData="
      }
    ],
    "live": [
      {
        "domain": "*",
        "gateway": "paytm",
        "api_secret": "API_SECRET",
        "api_key": "API_KEY",
        "redirect_path": "/transaction_status",
        "api_url": "https://pguat.paytm.com",
        "payment_request_endpoint": "/oltp-web/processTransaction",
        "transaction_status_endpoint": "/oltp/HANDLER_INTERNAL/getTxnStatus?JsonData=",
        "response_webhook": "https://yyhloe6kfg.execute-api.ap-south-1.amazonaws.com/prod/payment_response_proxy/http://bin.prayashm.com/qu0mllqu"
      }
    ]
  }
}`

**Comment by varevarao** [comment]
This seems to be related to the dynamic schema generation. Objects nested within arrays are not returning the expected properties.
Working on a fix.

**Comment by rokrsa** [comment]
Ensure that the JSON Editor is able to handle any kind of JSON file. it should not rely on a fixed/pre-defined structure.
